

train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: None
      split_file: datasets/NILM.json
      split_key: train
      repeat: 1
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 512
      scale_max: 4
      augment: true
      sample_q: 2000
  batch_size: 8

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: None
      split_file: datasets/NILM.json
      split_key: val
      # first_k: 10
      repeat: 1
      cache: none
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 512
      scale_max: 4
      sample_q: 2000
  batch_size: 8

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
  name: liif
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: true
    imnet_spec:
      name: mlp
      args:
        out_dim: 1
        hidden_list: [256, 256, 256, 256]

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
multi_step_lr:
  milestones: [200, 400, 600, 800]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
